
[functions.paypal-cancel]
enabled = true
verify_jwt = false
import_map = "./functions/paypal-cancel/deno.json"
entrypoint = "./functions/paypal-cancel/index.ts"

[functions.paypal-return]
enabled = true
verify_jwt = false
import_map = "./functions/paypal-return/deno.json"
entrypoint = "./functions/paypal-return/index.ts"

[functions.receive-paypal-ipn]
enabled = true
verify_jwt = false
import_map = "./functions/receive-paypal-ipn/deno.json"
entrypoint = "./functions/receive-paypal-ipn/index.ts"

[functions.create-paypal-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-paypal-order/deno.json"
entrypoint = "./functions/create-paypal-order/index.ts"

[functions.capture-paypal-order]
enabled = true
verify_jwt = false
import_map = "./functions/capture-paypal-order/deno.json"
entrypoint = "./functions/capture-paypal-order/index.ts"

[functions.create-voting-period]
enabled = true
verify_jwt = true
import_map = "./functions/create-voting-period/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-voting-period/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-voting-period/*.html" ]

[functions.record-donation]
enabled = true
verify_jwt = true
import_map = "./functions/record-donation/deno.json"
entrypoint = "./functions/record-donation/index.ts"

[functions.update-charity]
enabled = true
verify_jwt = true
import_map = "./functions/update-charity/deno.json"
entrypoint = "./functions/update-charity/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
import_map = "./functions/delete-account/deno.json"
entrypoint = "./functions/delete-account/index.ts"

[functions.close-voting-period]
enabled = true
verify_jwt = true
import_map = "./functions/close-voting-period/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/close-voting-period/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/close-voting-period/*.html" ]

